import type { Metadata } from "next";
import "./globals.css";
import 'primereact/resources/themes/saga-blue/theme.css'; // Or any other PrimeReact theme
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import { ClerkProvider } from '@clerk/nextjs';

// Metadata for SEO and document head
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
